alert_time_limit:
  days: 2
buffer_time:
  minutes: 15
es_host: search-bridgelogs-ed-fgc37p7jyn3y5l465bp7ik5lr4.us-east-1.es.amazonaws.com
es_port: 443
rules_folder: example_rules
run_every:
  minutes: 1
writeback_index: elastalert_status
